// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application"
import HelloController from "./hello_controller"
import ChatController from "./chat_controller"
import ChatInputController from "./chat_input_controller"
import MessageController from "./message_controller"
import ThemeController from "./theme_controller"

application.register("hello", HelloController)
application.register("chat", ChatController)
application.register("chat-input", ChatInputController)
application.register("message", MessageController)
application.register("theme", ThemeController)
