// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application"
import HelloController from "./hello_controller"
import ChatController from "./chat_controller"
import ChatInputController from "./chat_input_controller"
import MessageController from "./message_controller"
import ThemeController from "./theme_controller"
import ThemeSelectController from "./theme_select_controller"
import HistoryDrawerController from "./history_drawer_controller"
import LightboxController from "./lightbox_controller"
import FlashAlertController from "./flash_alert_controller"
import FormErrorsController from "./form_errors_controller"
import CharacterDetailsController from "./character_details_controller"
import CharacterFactsController from "./character_facts_controller"
import CharacterInstructionsController from "./character_instructions_controller"
import CharactersImagesController from "./characters_images_controller"
import AvatarCropDialogController from "./avatar_crop_dialog_controller"
import AvatarInputController from "./avatar_input_controller"
import AppModalController from "./app_modal_controller"
import CodeMirrorController from "./code_mirror_controller"
import TextareaAutosizeController from "./textarea_autosize_controller"
import AdminConsoleModalController from "./admin_console_modal_controller"
import AdminConsoleOpenerController from "./admin_console_opener_controller"
import AutocompleteController from "./autocomplete_controller"
import MissionControlLinkController from "./mission_control_link_controller"

application.register("hello", HelloController)
application.register("chat", ChatController)
application.register("chat-input", ChatInputController)
application.register("message", MessageController)
application.register("theme", ThemeController)
application.register("theme-select", ThemeSelectController)
application.register("history-drawer", HistoryDrawerController)
application.register("lightbox", LightboxController)
application.register("flash-alert", FlashAlertController)
application.register("form-errors", FormErrorsController)
application.register("character-details", CharacterDetailsController)
application.register("character-facts", CharacterFactsController)
application.register("character-instructions", CharacterInstructionsController)
application.register("characters-images", CharactersImagesController)
application.register("avatar-crop-dialog", AvatarCropDialogController)
application.register("avatar-input", AvatarInputController)
application.register("app-modal", AppModalController)
application.register("code-mirror", CodeMirrorController)
application.register("textarea-autosize", TextareaAutosizeController)
application.register("admin-console-modal", AdminConsoleModalController)
application.register("admin-console-opener", AdminConsoleOpenerController)
application.register("autocomplete", AutocompleteController)
application.register("mission-control-link", MissionControlLinkController)
